### ISSUE TITLE
Nohr bg artwork not visible on mobile Safari

### ISSUE THREAD

**Issue by mcglincy** [jdbann/exlibris#127] opened 2021-07-21 12:59 UTC
iPhone X, iOS 14.4.2

It's not visible when the page first loads (I see only a black screen), although when I scroll down I see a bit of the image visible behind the top of the yellow search widget. So maybe it's just got the wrong offset on mobile Safari?

**Comment by jdbann** [comment] 2021-07-21 15:06
Closing as duplicate of #110

**Closed by jdbann** 2021-07-21 15:06 UTC
